package modelo.entidad;
// Generated 12/11/2020 04:47:11 PM by Hibernate Tools 4.3.1



/**
 * Medicos generated by hbm2java
 */
public class Medicos  implements java.io.Serializable {


     private Integer idMedico;
     private String nombre;
     private int sala;
     private String especialidad;

    public Medicos() {
    }

    public Medicos(String nombre, int sala, String especialidad) {
       this.nombre = nombre;
       this.sala = sala;
       this.especialidad = especialidad;
    }
   
    public Integer getIdMedico() {
        return this.idMedico;
    }
    
    public void setIdMedico(Integer idMedico) {
        this.idMedico = idMedico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getSala() {
        return this.sala;
    }
    
    public void setSala(int sala) {
        this.sala = sala;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }




}


